spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_app?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: tailocphanhuu
    password: tailocphanhuu
  jpa:
    show-sql: true
    format_sql: true
